class exeptionDouble(Exception):
    pass

class exceptionInt(Exception):
    pass